config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :users, only: [ :new, :create, :edit ]
  
  # sessions
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  # show all movies
  get '/movies' => 'movies#index'

  # watched_movies
  post '/watched_movies/add' => 'watched_movies#create'
  get '/watched_movies/delete' => 'watched_movies#destroy'
  put '/watched_movies/update_favorite' => 'watched_movies#update_favorite'
  

  # profile
  get '/profile' => 'profile#index'
  get '/about-us' => 'about#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    validates :user_id, :movie_id, :presence => true, on: :create
    validates :movie_id, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :watched_movies, dependent: :destroy
  
  before_save :downcase_email, :capitalize_name

  validates :first_name, :last_name, :email, :presence => true, on: :create
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8 }, on: :create

  private 

  def downcase_email
    self.email = email.downcase
  end

  def capitalize_name
    self.first_name = first_name.capitalize
    self.last_name = last_name.capitalize
  end
end

app/models/watched_movie.rb
class WatchedMovie < ApplicationRecord
    belongs_to :user
    belongs_to :movie

    validates :user_id, :movie_id, :presence => true, on: :create
    validates :movie_id, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :danger, :info, :warning, :success
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/sessions/new' unless current_user
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @watched_movies_ids ||= current_user.watched_movies&.map{ |m| m.movie_id }
    @favorite_movies_ids ||= current_user.watched_movies&.map{ |m| m.movie_id if m.favorite }
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authorize

  def index
    @profile_movies ||= current_user.watched_movies.includes(:movie)
    @watched_movies ||= @profile_movies.select{ |movie| !movie.favorite }
    @favorite_movies ||= @profile_movies.select{ |movie| movie.favorite }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back #{current_user.first_name}"
      redirect_to profile_path
    else
      flash[:danger] = "Email and password combination not found."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user = User.new
  end

  def create 
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = "Welcome to Movie Tracker #{current_user.first_name}!"
      redirect_to movies_path
    else 
      flash[:danger] = user.errors.full_messages.join(", ") if user.errors.any?
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, 
      :last_name,
      :email, 
      :password, 
      :password_confirmation
      )
  end
end

app/controllers/watched_movies_controller.rb
class WatchedMoviesController < ApplicationController  
  def new
    watched_movie = WatchedMovie.new
  end
  
  def create
    watched_movie = WatchedMovie.new(watched_movie_params)
    watched_movie.save

    respond_to do |format|
      format.json
    end
  end

  def update_favorite
    favorite = WatchedMovie.find_by(movie_id: watched_movie_params[:movie_id]).update_attribute(:favorite, watched_movie_params[:favorite])
  end

  def destroy
    watched_movie = WatchedMovie.find_by(watched_movie_params).destroy
  end

  private

  def watched_movie_params
    params.require(:watched_movie).permit(
      :movie_id,
      :user_id,
      :favorite
    )
  end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to profile_path if current_user

    @movie_samples = Movie.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="text-center">
  <h1>About Us</h1>
  <p>This is a web-app created by Robert Garcia.</p> 
  <p>It allowed me to practive development with Ruby on Rails and other technologies.</p>
  <p>This page is still a work in progress.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/c1476fdb97.js" crossorigin="anonymous"></script>
  </head>
  <body>
      <% flash.each do |name, msg| %>
        <div class='container-fluid p-0' id="alert">
          <div class='alert alert-<%= name %> text-center fade show' role="alert">
            <%= msg %>
          </div>
        </div>
      <% end %>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Movie Tracker", root_path, class: "navbar-brand", id: "header" %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "Home", current_user ? profile_path : root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About Us", about_us_path, class: "nav-link" %>
          </li>
          <% if !current_user %>
            <li class="nav-item">
              <%= link_to "Login", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
            </li>
          <% else %>
            <%= link_to "Movies", movies_path, class: "nav-link" %>
            <%= link_to "Logout", logout_path, class: "nav-link" %>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <hr>
    <footer class="flex-container">
      <%= link_to "Home", current_user ? profile_path : root_path, class: "nav-link" %>
      <%= link_to "About Us", about_us_path, class: "nav-link" %>
    </footer>

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/index.html.erb
<div class="card-container">
  <% @movies.each do |movie|%>
    <%= render partial: "/shared/movie_card", locals: { m: movie, watched_movie: @watched_movies_ids.include?(movie.id),favorite: @favorite_movies_ids.include?(movie.id), icons: true }%>
  <% end %>
</div>

app/views/shared/_movie_card.html.erb
 <div class="card" data-movie-id=<%= m.id %> data-user-id=<%= current_user.id %>>
  <img src="https://image.tmdb.org/t/p/w500/<%= m.poster_path %>" class="card-img-top" alt="<%= m.title %>">
  <div class="card-body">
    <div class="text-container">
      <h5 class="card-title"><%= m.title %></h5>
      <p class="card-text"><%= m.overview %></p>
    </div>
    <% if icons %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="<%= watched_movie ? 'fas' : 'far' %> fa-bookmark fa-stack-1x fa-inverse"></i>
      </span>
      <span class="fa-stack fa-2x favorite <%= watched_movie ? '' : 'hidden' %>">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="<%= favorite ? 'fas' : 'far' %> fa-heart fa-stack-1x fa-inverse" data-favorite="true"></i>
      </span>   
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid p-4">
  <div class="row text-center">
    <div class="col-sm-12 col-md-6 col-lg-6 m-auto text-center">
        <h2>Simply complete the form and start tracking your movies today!</h2>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6">
      <%=form_for :user, url: '/users' do |f| %>
        <div class="grid-container">
          <%= f.label :first_name %> 
          <%= f.text_field :first_name, class: 'form-inputs' %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-inputs' %>
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-inputs' %>
          <%= f.label :password %> 
          <%= f.password_field :password, class: 'form-inputs' %>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-inputs' %>
        </div>
        
        <%= f.submit 'Sign Up', class: "btn btn-primary" %>
      <%end%>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="flex-container">
  <%= image_tag("/assets/paramount.jpg", class: "hero-image") %>
  <div class="hero-text">
    <h1>Welcome to Movie Tracker</h1>
    <p class="sub-text">A place for movie lovers to track and review movies they have seen! Best of all it's free to use.</p>
    <%= link_to  "Create Account", new_user_path, class: "btn btn-primary mt-4" %>
  </div>
</div>
<div class="flex-container" id="main-background">
  <div class="steps">
    <h2 class="step">Step 1</h2>
    <p>Create an account, all you need is an email address.</p>
  </div>
  <div class="steps">
    <h2 class="step">Step 2</h2>
    <p>Start tracking and rating movies.</p>
  </div>
  <div class="steps">
    <h2 class="step">Step 3</h2>
    <p>You'll never forget if you saw that bad movie.</p>
  </div>
</div>
<div class="flex-container">
  <% @movie_samples.each do |sample| %>
    <%= render partial: '/shared/movie_card', locals: { m: sample, watched_movie: false, favorite: false, icons: false } %>
  <% end %>
</div>
<div class="get-started-banner">
  <h2>What are you waiting for?</h2>
  <%= link_to  "Start Tracking Today", new_user_path, class: "btn btn-primary mt-4" %>
</div>